<?xml version="1.0" encoding="utf-8"?><Database Name="LGT_DRUG" Class="LGT_DRUGDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.111.28.132;Initial Catalog=LGT_DRUG;Persist Security Info=True;User ID=fusion" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LGT_DRUGConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MAS_ADMIN_BUTTON" Member="MAS_ADMIN_BUTTONs">
    <Type Name="MAS_ADMIN_BUTTON">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BTN_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BTN_URL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BTN_GROUP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDgroup" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="type_g" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ADMIN_GROUP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TARGET" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>