<?xml version="1.0" encoding="utf-8"?><Database Name="FDA_ADV" Class="Linq_ADVDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.111.28.132;Initial Catalog=FDA_ADV;Persist Security Info=True;User ID=fusion" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FDA_ADVConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FDATransaction" Member="FDATransactions">
    <Type Name="FDATransaction">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ApplicationNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="AccountTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AccountStatusId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccountFileName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SendFDADate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FDAReceiveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Citizen_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Authorize_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Officer_Infest" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Infest" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="U1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Ownner_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pvcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="discount" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FDAReceiveUpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AgentName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Agent_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateYear" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>